name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Git
        run: |
          git config --global user.name "${{ secrets.GITHUB_ACTOR }}"
          git config --global user.email "${{ secrets.GITHUB_ACTOR }}@users.noreply.github.com"
      - name: Install dependencies
        run: npm install
      - name: Build and deploy
        run: npm run deploy
